-- ===================================================
-- AI FEATURES DATABASE MIGRATION
-- Add tables and columns needed for AI features
-- ===================================================

-- 1. Add property_alerts table for commute-based alerts
CREATE TABLE IF NOT EXISTS public.property_alerts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  preferences jsonb NOT NULL,
  enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add AI usage tracking table
CREATE TABLE IF NOT EXISTS public.ai_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  feature text NOT NULL,
  tokens_used integer,
  cost numeric(10, 6),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_property_alerts_user_id ON public.property_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_property_alerts_enabled ON public.property_alerts(enabled);
CREATE INDEX IF NOT EXISTS idx_ai_usage_user_id ON public.ai_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_created_at ON public.ai_usage(created_at);

-- 4. Add coordinates index for faster location queries
CREATE INDEX IF NOT EXISTS idx_properties_coordinates ON public.properties(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_properties_location ON public.properties(location);

-- 5. Enable RLS on new tables
ALTER TABLE public.property_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies for property_alerts
CREATE POLICY "Users can view own alerts" 
  ON public.property_alerts FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own alerts" 
  ON public.property_alerts FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own alerts" 
  ON public.property_alerts FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own alerts" 
  ON public.property_alerts FOR DELETE 
  USING (auth.uid() = user_id);

-- 7. RLS Policies for ai_usage
CREATE POLICY "Users can view own AI usage" 
  ON public.ai_usage FOR SELECT 
  USING (auth.uid() = user_id OR public.is_admin() = true);

CREATE POLICY "System can insert AI usage" 
  ON public.ai_usage FOR INSERT 
  WITH CHECK (true);

-- 8. Add AI-generated flag to properties (optional)
ALTER TABLE public.properties 
ADD COLUMN IF NOT EXISTS ai_generated_description boolean DEFAULT false;

-- 9. Add commute_info jsonb column to properties (for caching)
ALTER TABLE public.properties 
ADD COLUMN IF NOT EXISTS commute_info jsonb;

-- 10. Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 11. Create trigger for property_alerts
DROP TRIGGER IF EXISTS update_property_alerts_updated_at ON public.property_alerts;
CREATE TRIGGER update_property_alerts_updated_at
    BEFORE UPDATE ON public.property_alerts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 12. Add user preferences for AI features
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS ai_preferences jsonb DEFAULT '{
  "enable_ai_descriptions": true,
  "enable_commute_alerts": true,
  "default_commute_mode": "driving",
  "office_location": null
}'::jsonb;

-- ===================================================
-- VERIFICATION QUERIES
-- ===================================================

-- Check if tables were created
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('property_alerts', 'ai_usage')
ORDER BY table_name;

-- Check property_alerts structure
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'property_alerts' 
AND table_schema = 'public'
ORDER BY ordinal_position;

-- Check indexes
SELECT indexname, tablename 
FROM pg_indexes 
WHERE schemaname = 'public' 
AND tablename IN ('property_alerts', 'ai_usage', 'properties')
ORDER BY tablename, indexname;

-- ===================================================
-- SAMPLE DATA (Optional - for testing)
-- ===================================================

-- Example alert (replace with actual user_id)
-- INSERT INTO public.property_alerts (user_id, preferences, enabled) VALUES (
--   'your-user-id-here',
--   '{
--     "office_location": {"latitude": 28.6139, "longitude": 77.2090},
--     "max_commute_minutes": 20,
--     "min_price": 5000000,
--     "max_price": 15000000,
--     "bedrooms": 3,
--     "property_type": "apartment",
--     "amenities": ["parking", "gym"]
--   }'::jsonb,
--   true
-- );

-- ===================================================
-- MIGRATION COMPLETE!
-- ===================================================
-- New Features Added:
-- ✅ Property alerts with commute preferences
-- ✅ AI usage tracking for cost monitoring
-- ✅ Optimized indexes for location queries
-- ✅ User AI preferences in profiles
-- ✅ Complete RLS policies
-- 
-- Next Steps:
-- 1. Run this migration in your Supabase SQL editor
-- 2. Set up Python backend with required API keys
-- 3. Configure frontend to use new AI endpoints
-- ===================================================
