-- ===================================================
-- COMPLETE DATABASE SETUP FOR SMARTESTATE
-- Run this script to set up everything from scratch
-- ===================================================

-- ===================================================
-- STEP 0: CLEAN UP (Remove old structures)
-- ===================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.is_admin() CASCADE;
DROP FUNCTION IF EXISTS increment_property_views(UUID) CASCADE;
DROP FUNCTION IF EXISTS increment_property_views(BIGINT) CASCADE;
DROP TABLE IF EXISTS public.inquiries CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.properties CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;
DROP TYPE IF EXISTS public.property_status CASCADE;
DROP TYPE IF EXISTS public.furnishing_type CASCADE;
DROP TYPE IF EXISTS public.property_age_type CASCADE;

-- ===================================================
-- STEP 1: ENUMS & TYPES
-- ===================================================
CREATE TYPE public.user_role AS ENUM ('admin', 'agent', 'seller', 'buyer');
CREATE TYPE public.property_status AS ENUM ('pending', 'active', 'rejected', 'sold');
CREATE TYPE public.furnishing_type AS ENUM ('furnished', 'semi-furnished', 'unfurnished');
CREATE TYPE public.property_age_type AS ENUM ('new', 'resale');

-- ===================================================
-- STEP 2: TABLES SETUP
-- ===================================================

-- 1. PROFILES TABLE
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name text,
  role user_role DEFAULT 'buyer',
  agency_name text,
  rera_number text,
  is_verified boolean DEFAULT false,
  phone text,
  experience_years integer,
  specialization text,
  office_address text,
  document_urls text[]
);

-- 2. PROPERTIES TABLE
CREATE TABLE public.properties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  title text NOT NULL,
  description text,
  price numeric,
  location text,
  area_sqft numeric,
  bedrooms int,
  bathrooms int,
  type text,
  images text[],
  video_url text,
  status property_status DEFAULT 'pending',
  posted_by uuid REFERENCES public.profiles(id) NOT NULL,
  latitude float,
  longitude float,
  furnishing_status furnishing_type DEFAULT 'unfurnished',
  property_age property_age_type DEFAULT 'new',
  floor_number integer,
  total_floors integer,
  year_built integer,
  amenities text[],
  ownership_docs text[]
);

-- 3. INQUIRIES TABLE
CREATE TABLE public.inquiries (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  name text NOT NULL,
  email text NOT NULL,
  message text,
  status text DEFAULT 'new' CHECK (status IN ('new', 'replied', 'closed')),
  response text,
  responded_at timestamp with time zone,
  responded_by uuid REFERENCES public.profiles(id),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. NOTIFICATIONS TABLE
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid REFERENCES public.profiles(id) NOT NULL,
  message text,
  is_read boolean DEFAULT false
);

-- ===================================================
-- STEP 3: FUNCTIONS & TRIGGERS
-- ===================================================

-- Auto-create profile when user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', ''), 
    COALESCE(new.raw_user_meta_data->>'role', 'buyer')::user_role
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role;
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ===================================================
-- STEP 4: STORAGE SETUP
-- ===================================================

-- Create storage bucket for property images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('property-images', 'property-images', true)
ON CONFLICT (id) DO NOTHING;

-- ===================================================
-- STEP 5: ROW LEVEL SECURITY (RLS)
-- ===================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- ===================================================
-- PROFILES POLICIES
-- ===================================================

CREATE POLICY "Public profiles are viewable by everyone" 
  ON public.profiles FOR SELECT 
  USING (true);

CREATE POLICY "Users can update own profile OR Admin can update any" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id OR public.is_admin() = true);

CREATE POLICY "Only Admin can delete profiles" 
  ON public.profiles FOR DELETE 
  USING (public.is_admin() = true);

-- ===================================================
-- PROPERTIES POLICIES
-- ===================================================

CREATE POLICY "Read access for properties" 
  ON public.properties FOR SELECT 
  USING (
    status = 'active' OR 
    auth.uid() = posted_by OR 
    public.is_admin() = true
  );

CREATE POLICY "Users can insert their own properties" 
  ON public.properties FOR INSERT 
  WITH CHECK (auth.uid() = posted_by);

CREATE POLICY "Owners and Admins can update properties" 
  ON public.properties FOR UPDATE 
  USING (
    auth.uid() = posted_by OR 
    public.is_admin() = true
  );

CREATE POLICY "Owners and Admins can delete properties" 
  ON public.properties FOR DELETE 
  USING (
    auth.uid() = posted_by OR 
    public.is_admin() = true
  );

-- ===================================================
-- INQUIRIES POLICIES
-- ===================================================

-- Anyone can submit inquiries
CREATE POLICY "Anyone can insert inquiries" 
  ON public.inquiries FOR INSERT 
  WITH CHECK (true);

-- Property owners, admins, and inquiry submitters can view inquiries
CREATE POLICY "Property owners can view inquiries" 
  ON public.inquiries FOR SELECT 
  USING (
    auth.uid() IN (
      SELECT posted_by FROM public.properties WHERE id = property_id
    ) OR 
    public.is_admin() = true OR
    auth.uid() = user_id
  );

-- Property owners and admins can update inquiries (to respond)
CREATE POLICY "Property owners can update inquiries" 
  ON public.inquiries FOR UPDATE 
  USING (
    auth.uid() IN (
      SELECT posted_by FROM public.properties WHERE id = property_id
    ) OR 
    public.is_admin() = true
  );

-- ===================================================
-- NOTIFICATIONS POLICIES
-- ===================================================

CREATE POLICY "Users can see own notifications" 
  ON public.notifications FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can insert notifications" 
  ON public.notifications FOR INSERT 
  WITH CHECK (public.is_admin() = true);

-- ===================================================
-- STORAGE POLICIES
-- ===================================================

CREATE POLICY "Public Access Images" 
  ON storage.objects FOR SELECT 
  USING (bucket_id = 'property-images');

CREATE POLICY "Authenticated upload" 
  ON storage.objects FOR INSERT 
  WITH CHECK (
    bucket_id = 'property-images' AND 
    auth.role() = 'authenticated'
  );

CREATE POLICY "Users delete own images" 
  ON storage.objects FOR DELETE 
  USING (
    bucket_id = 'property-images' AND 
    auth.uid() = owner
  );

-- ===================================================
-- VERIFICATION QUERIES
-- ===================================================

-- Check if all tables exist
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('profiles', 'properties', 'inquiries', 'notifications')
ORDER BY table_name;

-- Check inquiries table structure
SELECT column_name, data_type, column_default 
FROM information_schema.columns 
WHERE table_name = 'inquiries' 
AND table_schema = 'public'
ORDER BY ordinal_position;

-- Check RLS policies
SELECT schemaname, tablename, policyname, permissive, cmd
FROM pg_policies
WHERE tablename IN ('profiles', 'properties', 'inquiries', 'notifications')
ORDER BY tablename, policyname;

-- ===================================================
-- SETUP COMPLETE!
-- ===================================================
-- Next steps:
-- 1. Create your first admin user through the signup page
-- 2. Manually update their role to 'admin' in the profiles table:
--    UPDATE profiles SET role = 'admin' WHERE email = 'your-email@example.com';
-- 3. Test the application with different user roles
-- 
-- Features included:
-- ✅ User profiles with roles (admin, agent, seller, buyer)
-- ✅ Properties with full details and status management
-- ✅ Inquiry system with response tracking
-- ✅ Notifications system
-- ✅ Storage for property images
-- ✅ Complete RLS policies for security
-- 
-- Inquiry System Features:
-- ✅ Users can submit inquiries on properties
-- ✅ Property owners can view and respond to inquiries
-- ✅ Users can track their submitted inquiries
-- ✅ Admins can view and manage all inquiries
-- ✅ Status tracking (new, replied, closed)
-- ✅ Response timestamps and tracking
-- ===================================================
