-- ===================================================
-- COMPLETE DATABASE SETUP FOR SMARTESTATE
-- Run this script to set up everything from scratch
-- ===================================================

-- ===================================================
-- STEP 0: CLEAN UP (Remove old structures)
-- ===================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.is_admin() CASCADE;
DROP FUNCTION IF EXISTS increment_property_views(UUID) CASCADE;
DROP FUNCTION IF EXISTS increment_property_views(BIGINT) CASCADE;
DROP TABLE IF EXISTS public.inquiries CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.properties CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;
DROP TYPE IF EXISTS public.property_status CASCADE;
DROP TYPE IF EXISTS public.furnishing_type CASCADE;
DROP TYPE IF EXISTS public.property_age_type CASCADE;

-- ===================================================
-- STEP 1: ENUMS & TYPES
-- ===================================================
CREATE TYPE public.user_role AS ENUM ('admin', 'agent', 'seller', 'buyer');
CREATE TYPE public.property_status AS ENUM ('pending', 'active', 'rejected', 'sold');
CREATE TYPE public.furnishing_type AS ENUM ('furnished', 'semi-furnished', 'unfurnished');
CREATE TYPE public.property_age_type AS ENUM ('new', 'resale');

-- ===================================================
-- STEP 2: TABLES SETUP
-- ===================================================

-- 1. PROFILES TABLE
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name text,
  role user_role DEFAULT 'buyer',
  agency_name text,
  rera_number text,
  is_verified boolean DEFAULT false,
  phone text,
  experience_years integer,
  specialization text,
  office_address text,
  document_urls text[]
);

-- 2. PROPERTIES TABLE
CREATE TABLE public.properties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  title text NOT NULL,
  description text,
  price numeric,
  location text,
  pincode text,
  unit_number text,
  area_sqft numeric,
  bedrooms int,
  bathrooms int,
  type text,
  images text[],
  video_url text,
  status property_status DEFAULT 'pending',
  posted_by uuid REFERENCES public.profiles(id) NOT NULL,
  latitude float,
  longitude float,
  furnishing_status furnishing_type DEFAULT 'unfurnished',
  property_age property_age_type DEFAULT 'new',
  floor_number integer,
  total_floors integer,
  year_built integer,
  amenities text[],
  ownership_docs text[],
  ai_generated_description boolean DEFAULT false,
  commute_info jsonb
);

-- 3. INQUIRIES TABLE
CREATE TABLE public.inquiries (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  name text NOT NULL,
  email text NOT NULL,
  message text,
  status text DEFAULT 'new' CHECK (status IN ('new', 'replied', 'closed')),
  response text,
  responded_at timestamp with time zone,
  responded_by uuid REFERENCES public.profiles(id),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. NOTIFICATIONS TABLE
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid REFERENCES public.profiles(id) NOT NULL,
  message text,
  is_read boolean DEFAULT false
);

-- 5. SAVED PROPERTIES TABLE
CREATE TABLE public.saved_properties (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  property_id bigint REFERENCES public.properties(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, property_id)
);

-- 6. PROPERTY ALERTS TABLE (AI Features)
CREATE TABLE public.property_alerts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  preferences jsonb NOT NULL,
  enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. AI USAGE TRACKING TABLE
CREATE TABLE public.ai_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  feature text NOT NULL,
  tokens_used integer,
  cost numeric(10, 6),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ===================================================
-- STEP 3: FUNCTIONS & TRIGGERS
-- ===================================================

-- Auto-create profile when user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger 
LANGUAGE plpgsql 
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, ai_preferences)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', ''), 
    COALESCE(new.raw_user_meta_data->>'role', 'buyer')::user_role,
    '{
      "enable_ai_descriptions": true,
      "enable_commute_alerts": true,
      "default_commute_mode": "driving",
      "office_location": null
    }'::jsonb
  )
  ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role;
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_property_alerts_updated_at
    BEFORE UPDATE ON public.property_alerts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ===================================================
-- STEP 4: STORAGE SETUP
-- ===================================================

-- Create storage bucket for property images
INSERT INTO storage.buckets (id, name, public) 
VALUES ('property-images', 'property-images', true)
ON CONFLICT (id) DO NOTHING;

-- ===================================================
-- STEP 5: INDEXES FOR PERFORMANCE
-- ===================================================

CREATE INDEX IF NOT EXISTS idx_properties_coordinates ON public.properties(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_properties_location ON public.properties(location);
CREATE INDEX IF NOT EXISTS idx_properties_status ON public.properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_posted_by ON public.properties(posted_by);
CREATE INDEX IF NOT EXISTS idx_saved_properties_user_id ON public.saved_properties(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_properties_property_id ON public.saved_properties(property_id);
CREATE INDEX IF NOT EXISTS idx_property_alerts_user_id ON public.property_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_property_alerts_enabled ON public.property_alerts(enabled);
CREATE INDEX IF NOT EXISTS idx_ai_usage_user_id ON public.ai_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_created_at ON public.ai_usage(created_at);
CREATE INDEX IF NOT EXISTS idx_inquiries_property_id ON public.inquiries(property_id);
CREATE INDEX IF NOT EXISTS idx_inquiries_user_id ON public.inquiries(user_id);

-- ===================================================
-- STEP 6: ROW LEVEL SECURITY (RLS)
-- ===================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_usage ENABLE ROW LEVEL SECURITY;

-- ===================================================
-- PROFILES POLICIES
-- ===================================================

CREATE POLICY "Public profiles are viewable by everyone" 
  ON public.profiles FOR SELECT 
  USING (true);

CREATE POLICY "Users can update own profile OR Admin can update any" 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id OR public.is_admin() = true);

CREATE POLICY "Only Admin can delete profiles" 
  ON public.profiles FOR DELETE 
  USING (public.is_admin() = true);

-- ===================================================
-- PROPERTIES POLICIES
-- ===================================================

CREATE POLICY "Read access for properties" 
  ON public.properties FOR SELECT 
  USING (
    status = 'active' OR 
    auth.uid() = posted_by OR 
    public.is_admin() = true
  );

CREATE POLICY "Users can insert their own properties" 
  ON public.properties FOR INSERT 
  WITH CHECK (auth.uid() = posted_by);

CREATE POLICY "Owners and Admins can update properties" 
  ON public.properties FOR UPDATE 
  USING (
    auth.uid() = posted_by OR 
    public.is_admin() = true
  );

CREATE POLICY "Owners and Admins can delete properties" 
  ON public.properties FOR DELETE 
  USING (
    auth.uid() = posted_by OR 
    public.is_admin() = true
  );

-- ===================================================
-- INQUIRIES POLICIES
-- ===================================================

-- Anyone can submit inquiries
CREATE POLICY "Anyone can insert inquiries" 
  ON public.inquiries FOR INSERT 
  WITH CHECK (true);

-- Property owners, admins, and inquiry submitters can view inquiries
CREATE POLICY "Property owners can view inquiries" 
  ON public.inquiries FOR SELECT 
  USING (
    auth.uid() IN (
      SELECT posted_by FROM public.properties WHERE id = property_id
    ) OR 
    public.is_admin() = true OR
    auth.uid() = user_id
  );

-- Property owners and admins can update inquiries (to respond)
CREATE POLICY "Property owners can update inquiries" 
  ON public.inquiries FOR UPDATE 
  USING (
    auth.uid() IN (
      SELECT posted_by FROM public.properties WHERE id = property_id
    ) OR 
    public.is_admin() = true
  );

-- ===================================================
-- NOTIFICATIONS POLICIES
-- ===================================================

CREATE POLICY "Users can see own notifications" 
  ON public.notifications FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can insert notifications" 
  ON public.notifications FOR INSERT 
  WITH CHECK (public.is_admin() = true);

-- ===================================================
-- SAVED PROPERTIES POLICIES
-- ===================================================

CREATE POLICY "Users can view their own saved properties"
  ON public.saved_properties FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can save properties"
  ON public.saved_properties FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unsave properties"
  ON public.saved_properties FOR DELETE
  USING (auth.uid() = user_id);

-- ===================================================
-- PROPERTY ALERTS POLICIES
-- ===================================================

CREATE POLICY "Users can view own alerts" 
  ON public.property_alerts FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own alerts" 
  ON public.property_alerts FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own alerts" 
  ON public.property_alerts FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own alerts" 
  ON public.property_alerts FOR DELETE 
  USING (auth.uid() = user_id);

-- ===================================================
-- AI USAGE POLICIES
-- ===================================================

CREATE POLICY "Users can view own AI usage" 
  ON public.ai_usage FOR SELECT 
  USING (auth.uid() = user_id OR public.is_admin() = true);

CREATE POLICY "System can insert AI usage" 
  ON public.ai_usage FOR INSERT 
  WITH CHECK (true);

-- ===================================================
-- STORAGE POLICIES
-- ===================================================

CREATE POLICY "Public Access Images" 
  ON storage.objects FOR SELECT 
  USING (bucket_id = 'property-images');

CREATE POLICY "Authenticated upload" 
  ON storage.objects FOR INSERT 
  WITH CHECK (
    bucket_id = 'property-images' AND 
    auth.role() = 'authenticated'
  );

CREATE POLICY "Users delete own images" 
  ON storage.objects FOR DELETE 
  USING (
    bucket_id = 'property-images' AND 
    auth.uid() = owner
  );

-- ===================================================
-- STEP 7: ADD AI PREFERENCES TO PROFILES
-- ===================================================

ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS ai_preferences jsonb DEFAULT '{
  "enable_ai_descriptions": true,
  "enable_commute_alerts": true,
  "default_commute_mode": "driving",
  "office_location": null
}'::jsonb;

-- ===================================================
-- VERIFICATION QUERIES
-- ===================================================

-- Check if all tables exist
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('profiles', 'properties', 'inquiries', 'notifications', 'saved_properties', 'property_alerts', 'ai_usage')
ORDER BY table_name;

-- Check properties table structure
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'properties' 
AND table_schema = 'public'
ORDER BY ordinal_position;

-- Check RLS policies
SELECT schemaname, tablename, policyname, permissive, cmd
FROM pg_policies
WHERE tablename IN ('profiles', 'properties', 'inquiries', 'notifications', 'saved_properties', 'property_alerts', 'ai_usage')
ORDER BY tablename, policyname;

-- ===================================================
-- SETUP COMPLETE!
-- ===================================================
-- Next steps:
-- 1. Create your first admin user through the signup page
-- 2. Manually update their role to 'admin' in the profiles table:
--    UPDATE profiles SET role = 'admin' WHERE id = 'your-user-id';
-- 3. Test the application with different user roles
-- 
-- Features included:
-- ✅ User profiles with roles (admin, agent, seller, buyer)
-- ✅ Properties with full details and status management
-- ✅ Multiple image upload support (images array)
-- ✅ Video and ownership documents support
-- ✅ Inquiry system with response tracking
-- ✅ Notifications system
-- ✅ Saved properties functionality
-- ✅ Property alerts with commute preferences (AI features)
-- ✅ AI usage tracking for cost monitoring
-- ✅ AI preferences per user
-- ✅ Storage for property images, videos, and documents
-- ✅ Complete RLS policies for security
-- ✅ Performance indexes for faster queries
-- 
-- Inquiry System Features:
-- ✅ Users can submit inquiries on properties
-- ✅ Property owners can view and respond to inquiries
-- ✅ Users can track their submitted inquiries
-- ✅ Admins can view and manage all inquiries
-- ✅ Status tracking (new, replied, closed)
-- ✅ Response timestamps and tracking
-- 
-- AI Features:
-- ✅ Commute-based property alerts
-- ✅ AI-generated property descriptions
-- ✅ Usage tracking and cost monitoring
-- ✅ User preferences for AI features
-- ===================================================
